---
url: https://www.habitaclia.com/alquiler-barcelona-{page}.htm
method: GET
query:
  ordenar: mas_recientes
parameters:
  - name: page
    schema: index
    value: 1
headers:
  User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
  Accept-Language: en-US,en;q=0.5
