---
method: GET
url: https://www.idealista.com/alquiler-viviendas/barcelona-barcelona/pagina-{page}.htm
query:
    ordenado-por: fecha-publicacion-desc
headers:
  User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
  Accept-Language: en-US,en;q=0.5
