---
item:
  path: .propertyCard
fieldList:
  reference:
    path:
    source: list-item
  url:
    path: .propertyCard__description--title
    source: href
  title:
    path: .propertyCard__description--title
    source: title
  price:
    path: .propertyCard__price--value
    source: _text
    purge: /\D+/
  picture:
    path: .propertyCard__carousel img
    source: srcset
  address:
    path: .propertyCard__location p
    source: _text
  zip_code:
  latitude:
  longitude:
  rooms:
    path: .propertyCard__details li:nth-child(2)
    source: _text
    purge: /[^\d]+/
  size:
    path: .propertyCard__details li:nth-child(1)
    source: _text
    purge: /\D+2/
  bathrooms:
    path: .propertyCard__details li:nth-child(3)
    source: _text
    purge: /[^\d]+/
  floor:
page:
  next_page:
  paginator:
    path: .pagination li
    source: _text
  total_items:
  current:
  total_pages:
