---
item:
  path: .list-items .js-list-item
fieldList:
  reference:
    path:
    source: data-id
  url:
    path:
    source: data-href
  title:
    path: .list-item-title a
    source: title
  price:
    path: .list-item-price .font-2
    source: _text
    purge: /[^\d]+/
  picture:
    path: .image img
    source: src
  address:
    path: .list-item-location span
    source: _text
  zip_code:
  latitude:
  longitude:
  rooms:
    path: .list-item-feature
    source: _text
    purge: /.*m2\s*-\s*|\s*habita.*/
  size:
    path: .list-item-feature
    source: _text
    purge: /m2\s*-.*/
  bathrooms:
  floor:
page:
  next_page:
  paginator:
    path: .pagination li
    source: _text
  total_items:
  current:
  total_pages:
