---
item:
  path: .extended-item
fieldList:
  reference:
    path:
    source: data-adid
  url:
    path: .item-link
    source: href
  title:
    path: .item-link
    source: title
  price:
    path: .item-info-container .item-price
    source: _text
    purge: /[^\d]+/
  picture:
    path: picture.item-multimedia div.placeholder img
    source: src
  address:
    path: .item-link
    source: _text
    purge: /.*?\s+en\s+/
  zip_code:
  latitude:
  longitude:
  rooms:
    path: .item-detail:nth-child(1)
    source: _text
    purge: /[^\d]+/
  size:
    path: .item-detail:nth-child(2)
    source: _text
    purge: /[^\d]+/
  bathrooms:
  floor:
    path: .item-detail:nth-child(3)
    source: _text
    purge: /\d+ horas/
page:
  next_page:
  paginator:
    path: .pagination li
    source: _text
  total_items:
  current:
  total_pages:
