---
item: .extended-item
fieldList:
  - reference: "@data-adid"
  - url: .item-link@href
  - title: .item-link@title
  - price: .item-info-container .item-price@_text
    sanitize: /[^\d]+/
  - picture: picture.item-multimedia div.placeholder img@src
  - rooms: .item-detail:nth-child(1)@_text
    sanitize: /[^\d]+/
  - size: .item-detail:nth-child(2)@_text
    sanitize: /[^\d]+/
  - bathrooms:
  - floor: .item-detail:nth-child(3)@_text
page:
  paginator: .pagination li@_text
