---
item:
  path: results
fieldList:
  reference:
    path: realEstate.id
  url:
    path: seo.url
  title:
    path: realEstate.title
  price:
    path: realEstate.price.value
  picture:
    path: realEstate.properties[0].photo.urls.small
  rooms:
    path: realEstate.properties[0].rooms
  size:
    path: realEstate.properties[0].surface
  bathrooms:
    path: realEstate.properties[0].bathrooms
  floor:
    path: realEstate.properties[0].floor.abbreviation
page:
  next_page:
  paginator:
  total_items:
  current:
    path: currentPage
  total_pages:
    path: maxPages
