---
item:
  path: .rating__new
fieldList:
  reference:
    path: .results__link
    source: data-id
  url:
    path: .results__link
    source: data-href
  title:
    path: .listing__title__text
    source: _text
  price:
    path: .result__details__price span
    source: _text
    purge: /[^\d]+/
  picture:
    path: .listing_list__cover img.desktopImg
    source: data-lazy
  rooms:
    path: .summary-item.rooms span.rooms
    source: _text
    purge: /[^\d]+/
  size:
    path: .summary-item.size span.size
    source: _text
    purge: /[^\d]+/
  bathrooms:
    path: .summary-item.rooms span.bathrooms
    source: _text
    purge: /[^\d]+/
  floor:
page:
  paginator:
    path: .pagination-bar .pagination__link
    source: _text
  total_items:
  current:
  total_pages:
